pipeline {
    agent any

    stages {
        stage('Create Python Virtual Environment') {
            steps {
                    sh 'pip install pipenv'
                    sh 'pipenv install'
            }
        }
        stage('Perform initial Hash Comparision') {
            steps {
                sh 'pipenv run pytest ./scripts/test_integrity_checker.py -s --test-object "${imagePath}" --initial-hash "${initialHash}"'
            }
        }
        stage('Perform File System Analysis') {
            steps {
                sh 'pipenv run python scripts/image_analyzer.py --image-path "${imagePath}"'
            }
        }
    }
}
